DEFAULT_TZ = "Europe/Moscow"
DEFAULT_PRESENCE = "with toy soldier"
DEFAULT_PREFIX = "d?"
DEV_LOG_CHANNEL_ID = 123
OWNER_ID = 576322791129743361
SHARD_COUNT = 1
SHARD_IDS = [
  0
]
COGS = [
  "src.cogs.CuteStuff",
  "src.cogs.Events",
  "src.cogs.ErrorHandler",
  "src.cogs.ServerAdmin",
  "src.cogs.Owner",
  "src.cogs.Meta",
  "src.cogs.ToDo",
  "src.cogs.Fun",
  "src.cogs.Memes",
  "src.cogs.Help"
]
KARMA_PHRASES = [
  "have a nice day"
]

[WEBHOOK]
NAME = "Defrabot"
AVATAR_URL = ""
LOGGING_URL = "https://discordapp.com/api/webhooks/000000000000/asdasdasdas1q234123dsgdfcg"

[DATABASE]
USER = "username"
PASSWORD = "password"
DATABASE = "DB name"
HOST = "IP addr"
PORT = 5432

[SECURITY]
SECRET_KEY = "some random thing must be here"

[API_KEYS]
CATS = "asdasd"
YANDEX = "blablabla"

[EMOJIS]
BOOK = '<:book:713686279497318430>'
FIRST_PAGE = '<:first_page:713690043964719204>'
LAST_PAGE = '<:last_page:713690043729838131>'
PREVIOUS_PAGE = '<:previous_page:706576101844975716>'
NEXT_PAGE = '<:next_page:706576101719277629>'
STOP_PAGES = '<:stop:706576101681528853>'
